name: CI

permissions:
  contents: write

on:
  push:
    branches: [ "QA", "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Application
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [[ -z "$deploy_url" ]]; then
            echo "Error: deploy_url is not set!"
            exit 1
          fi
          echo "Triggering deployment..."
          curl -v "$deploy_url"
          sleep 60

  chrome-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.6.0'
      - name: Install dependencies
        run: |
          cd ./src/test
          npm install
          npm install typescript
      - name: Run Chrome Tests
        run: |
          cd ./src/test
          npx tsc
          for file in *chrome*.js; do node "$file"; done
      - name: Upload Chrome Logs
        run: ls -l ./src/test/logs

  firefox-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.6.0'
      - name: Install dependencies
        run: |
          cd ./src/test
          npm install
          npm install typescript
      - name: Run Firefox Tests
        run: |
          cd ./src/test
          npx tsc
          for file in *firefox*.js; do node "$file"; done
      - name: Upload Firefox Logs
        run: ls -l ./src/test/logs

  edge-tests:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.6.0'
      - name: Install dependencies
        run: |
          cd ./src/test
          npm install
          npm install typescript
      - name: Install Edge Browser
        run: choco install microsoft-edge
      - name: Run Edge Tests
        run: |
          cd ./src/test
          npx tsc
          for file in *edge*.js; do node "$file"; done
      - name: Upload Edge Logs
        run: ls -l ./src/test/logs

  safari-tests:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.6.0'
      - name: Install dependencies
        run: |
          cd ./src/test
          npm install
          npm install typescript
      - name: Set up SafariDriver
        run: sudo safaridriver --enable
      - name: Run Safari Tests
        run: |
          cd ./src/test
          npx tsc
          for file in *safari*.js; do node "$file"; done
      - name: Upload Safari Logs
        run: ls -l ./src/test/logs
