name: CI

on:
  pull_request:
    branches: [ "main", "QA", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Ensure repo is cloned

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.6.0'  # ✅ Use correct Node.js version

      - name: Check directory structure
        run: ls -R  # ✅ Debugging step to see if `src/test` exists

      - name: Install dependencies inside /test
        run: |
          if [ -f "./src/test/package.json" ]; then 
            cd ./src/test
            npm install
          else
            echo "Error: ./src/test/package.json not found!"
            exit 1
          fi

      - name: Run tests
        working-directory: ./src/test  # ✅ Set the working directory
        run: |
          npx tsc
          node html-testing.js
        continue-on-error: false
